pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: true
        script:
          - git clone --bare git@github.com:asha8411p/test.git
          - cd test.git
          - git push --mirror git@github.com:asha8411p/test.git
