image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Sync to GitHub
        script:
          - git remote add github https://x-access-token:$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T@github.com/asha8411p/https://github.com/asha8411p/test.git
          - git push github master
