image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Sync to GitHub
        script:
          - git remote add all git@github.com:asha8411p/test.git
          - git push all 
          - git fetch all 