image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Sync to GitHub
        script:
          - git remote add --mirror=push git@github.com:asha8411p/test.git
          - git push github main