image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Sync to GitHub
        script:
          - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - git remote add github git@github.com:asha8411p/test.git
          - git pull github main
          - git push github HEAD:main

