image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Sync to GitHub
        script:
          - git config --local credential.helper ""
          - GIT_TOKEN="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T"
          - git push "https://x-access-token:$GIT_TOKEN@github.com/asha8411p/test.git" HEAD:main