image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Sync to GitHub
        script:
          - git config --global credential.helper store
          - git remote add github https://github.com/asha8411p/test.git
          - git push github master
